// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockConsumer is an autogenerated mock type for the Consumer type
type MockConsumer struct {
	mock.Mock
}

type MockConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsumer) EXPECT() *MockConsumer_Expecter {
	return &MockConsumer_Expecter{mock: &_m.Mock}
}

// RunConsume provides a mock function with given fields: ctx, handler
func (_m *MockConsumer) RunConsume(ctx context.Context, handler func([]byte) error) error {
	ret := _m.Called(ctx, handler)

	if len(ret) == 0 {
		panic("no return value specified for RunConsume")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func([]byte) error) error); ok {
		r0 = rf(ctx, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConsumer_RunConsume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunConsume'
type MockConsumer_RunConsume_Call struct {
	*mock.Call
}

// RunConsume is a helper method to define mock.On call
//   - ctx context.Context
//   - handler func([]byte) error
func (_e *MockConsumer_Expecter) RunConsume(ctx interface{}, handler interface{}) *MockConsumer_RunConsume_Call {
	return &MockConsumer_RunConsume_Call{Call: _e.mock.On("RunConsume", ctx, handler)}
}

func (_c *MockConsumer_RunConsume_Call) Run(run func(ctx context.Context, handler func([]byte) error)) *MockConsumer_RunConsume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func([]byte) error))
	})
	return _c
}

func (_c *MockConsumer_RunConsume_Call) Return(_a0 error) *MockConsumer_RunConsume_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConsumer_RunConsume_Call) RunAndReturn(run func(context.Context, func([]byte) error) error) *MockConsumer_RunConsume_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with given fields:
func (_m *MockConsumer) Stop() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConsumer_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockConsumer_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockConsumer_Expecter) Stop() *MockConsumer_Stop_Call {
	return &MockConsumer_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockConsumer_Stop_Call) Run(run func()) *MockConsumer_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConsumer_Stop_Call) Return(_a0 error) *MockConsumer_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConsumer_Stop_Call) RunAndReturn(run func() error) *MockConsumer_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConsumer creates a new instance of MockConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsumer {
	mock := &MockConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
