// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUUUIDGenerator is an autogenerated mock type for the UUUIDGenerator type
type MockUUUIDGenerator struct {
	mock.Mock
}

type MockUUUIDGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUUUIDGenerator) EXPECT() *MockUUUIDGenerator_Expecter {
	return &MockUUUIDGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields:
func (_m *MockUUUIDGenerator) Generate() uuid.UUID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	return r0
}

// MockUUUIDGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockUUUIDGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *MockUUUIDGenerator_Expecter) Generate() *MockUUUIDGenerator_Generate_Call {
	return &MockUUUIDGenerator_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *MockUUUIDGenerator_Generate_Call) Run(run func()) *MockUUUIDGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUUUIDGenerator_Generate_Call) Return(_a0 uuid.UUID) *MockUUUIDGenerator_Generate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUUUIDGenerator_Generate_Call) RunAndReturn(run func() uuid.UUID) *MockUUUIDGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUUUIDGenerator creates a new instance of MockUUUIDGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUUUIDGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUUUIDGenerator {
	mock := &MockUUUIDGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
