// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Feed struct {
	ID            uuid.UUID
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	Name          string
	Url           string
	LastFetchedAt pgtype.Timestamp
}

type FeedFollow struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	FeedID    uuid.UUID
	UserID    uuid.UUID
}

type PendingUser struct {
	ID        uuid.UUID
	Email     string
	Name      string
	Status    string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Post struct {
	ID          uuid.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	Title       string
	Description pgtype.Text
	Url         string
	PublishedAt pgtype.Timestamp
	FeedID      uuid.UUID
}

type User struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Email     string
	Name      string
}
