services:
  jaeger:
    image: jaegertracing/all-in-one:1.41
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # gRPC for collector
      - "14268:14268"  # HTTP endpoint

  otel-collector:
    image: otel/opentelemetry-collector:0.79.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317"    # gRPC receiver for OTLP traces
      - "4318:4318"    # HTTP receiver for OTLP traces
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml